@baseUrl = http://localhost:3000

GET {{baseUrl}}/events

###
# @name createEvent
POST {{baseUrl}}/events
Content-Type: application/json

{
    "name": "new event 3",
    "description": "description of new event",
    "date": "2024-06-18T11:45:23.000Z",
    "price": 200
}
###

@eventId = {{createEvent.response.body.id}}

###
GET {{baseUrl}}/events/{{eventId}}

###
PATCH {{baseUrl}}/events/{{eventId}}
Content-Type: application/json

{
    "name": "new event alterado",
    "description": "description of new event",
    "date": "2024-06-18T11:45:23.000Z",
    "price": 200
}

### 
DELETE {{baseUrl}}/events/{{eventId}}

###
GET {{baseUrl}}/events/{{eventId}}/spots

###
# @name createSpot
POST {{baseUrl}}/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A4"
}
###
POST {{baseUrl}}/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A5"
}
###
POST {{baseUrl}}/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A6"
}
###

@spotId = {{createSpot.response.body.id}}

###
GET {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}

###
PATCH {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
    "name": "A1"
}

### 
DELETE {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}

###
POST {{baseUrl}}/events/{{eventId}}/reserve
Content-Type: application/json

{
    "spots": ["A4","A5","A6"],
    "email": "email@test.com",
    "ticket_kind": ["full", "full", "half"],
    "price": 200
}