services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
        - app-network
    depends_on:
      - db
  db:
    image: 'postgres:16'
    ports:
        - 9002:5432
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - 'database:/var/lib/postgresql/data'
    networks:
        - app-network

networks:
  app-network:
      driver: bridge
volumes:
  database:
      driver: local